export const COLLECTIONS_PAGE_SIZE = 10;
export const COLLECTIONS_SHOP_PAGE_SIZE = 12;
export const COLLECTION_DETAIL_PRODUCTS_PAGE_SIZE = 12;
export const COLLECTIONS_SEARCH_DEBOUNCE_MS = 400;
export const COLLECTION_PRODUCT_SEARCH_LIMIT = 25;
export const TRENDING_COLLECTIONS_LIMIT = 8;
export const WEEKLY_COLLECTION_PRODUCT_PREVIEW = 4;

export const defaultCollections = [];
